name: check

on:
  push:
    branches:
      - '**'
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Log into production account
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::130607246975:role/ci-base-access
          role-session-name: dss
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Checkstyle
        uses: gradle/gradle-build-action@v3
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
          arguments: checkstyleMain checkstyleTest
      - name: PMD
        uses: gradle/gradle-build-action@v3
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
          arguments: pmdMain pmdTest
      - name: Test
        uses: gradle/gradle-build-action@v3
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
          arguments: test
