name: check

on:
  push:
    branches:
      - '**'
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Checkstyle
        uses: gradle/gradle-build-action@v2
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
          arguments: checkstyleMain checkstyleTest
      - name: PMD
        uses: gradle/gradle-build-action@v3
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
          arguments: pmdMain pmdTest
      - name: Test
        uses: gradle/gradle-build-action@v3
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
          arguments: test
