name: check

on:
  push:
    branches:
      - '**'
  workflow_call:

jobs:
  check:
    runs-on: [self-hosted, java-small]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Checkstyle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checkstyleMain checkstyleTest
      - name: PMD
        uses: gradle/gradle-build-action@v2
        with:
          arguments: pmdMain pmdTest
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
