name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  check:
    uses: ./.github/workflows/check.yml
  publish:
    needs: check
    runs-on: [self-hosted, small]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Build sourcesJar and javadocJar
        uses: gradle/gradle-build-action@v2
        with:
          arguments: sourcesJar javadocJar
      - name: Publish to MavenCentral
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishMavenPublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  github-release:
    needs: publish
    runs-on: [self-hosted, small]
    steps:
      - uses: actions/checkout@v3
      - name: Extract release notes
        id: release_notes
        uses: ffurrer2/extract-release-notes@v1
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          discussionCategory: Announcements
