name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  check:
    uses: ./.github/workflows/check.yml
  publish:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Log into production account
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::130607246975:role/ci-base-access
          role-session-name: dss
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Build sourcesJar and javadocJar
        uses: gradle/gradle-build-action@v3
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
          arguments: sourcesJar javadocJar
      - name: Publish to MavenCentral
        uses: gradle/gradle-build-action@v3
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
          arguments: publishMavenPublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  github-release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract release notes
        id: release_notes
        uses: ffurrer2/extract-release-notes@v1
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          discussionCategory: Announcements
