name: Repository Maintenance

on:
  push:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}${{ github.ref_name != github.event.repository.default_branch && github.ref || github.run_id }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  dependency-submission:
    name: Dependency Submission
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.2.1
      - uses: actions/setup-java@v4.4.0
        name: Setup Java
        with:
          distribution: temurin
          java-version: 21
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4.1.0
        with:
          gradle-version: wrapper
          dependency-graph: generate-and-submit
          # Include only relevant configurations
          dependency-graph-include-configurations: '(implementation|api|compileClasspath|runtimeClasspath)'
